version: "2"
services:
  nginx:
    image: "nginx:stable"
    container_name: nginx
    # restart: always
    hostname: nginx
    volumes:
      - ./nginx/fastcgi.conf:/etc/nginx/fastcgi.conf
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www
    ports:
      - "80:80"
    links:
      - "php-fpm"
    depends_on:
      - php-fpm
    network_mode: "bridge"

  php-fpm:
    image: "rodrixcornell/ubuntu-php:7.2-fpm"
    container_name: php-fpm
    # restart: always
    hostname: php-fpm
    volumes:
      - .:/var/www
    network_mode: "bridge"